##numpy array operations


In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("basic slicing", arr[2:7])
print("with step", arr[1:8:2])
print("negatiuve slicing", arr[:-3])

basic slicing [3 4 5 6 7]
with step [2 4 6 8]
negatiuve slicing [1 2 3 4 5 6]


In [5]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("specific element", arr_2d[0,2])
print("entire row:", arr_2d[1])
print(arr_2d[: 1])

specific element 3
entire row: [4 5 6]
[[1 2 3]]


##sorting

In [6]:
unsorted = np.array([3,2,5,6,4,1])
print("sorted array", np.sort(unsorted))
arr_2d_unsorted = np.array([[3,2], [69,4], [5,0]])
print("sorted array by column", np.sort(arr_2d_unsorted, axis=0))

sorted array [1 2 3 4 5 6]
sorted array by column [[ 3  0]
 [ 5  2]
 [69  4]]


#filter


In [7]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers%2 ==0]
print("even number", even_number)

even number [ 2  4  6  8 10]


##filter with mask

In [8]:
mask = numbers >5 
print("masked numbers", numbers[mask])

masked numbers [ 6  7  8  9 10]


##fancy indexing vs np.where()

In [11]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where", numbers[where_result])

[1 3 5]
NP where [ 6  7  8  9 10]


In [13]:
condition_array = np.where(numbers > 5, numbers*4, numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


##adding and removing data

In [15]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1,arr2))
print(combined)


[1 2 3 4 5 6]


##array compatibilty

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6, 7])
c = np.array([7,8,9])

print("Compatibilty shapes", a.shape == b.shape) #returns true if shape is same for both a and b 

Compatibilty shapes False


In [18]:
original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]


In [19]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)
print("array after deleteion", deleted)

array after deleteion [1 2 4 5]
