In [28]:
import pandas as pd

In [29]:
import numpy as np

In [30]:
miles = pd.DataFrame({'farthest_run_mi': [50,62, np.nan, 100, 26, 13, 31, 50]})

In [31]:
miles

,farthest_run_mi
0,50.0
1,62.0
2,NaN
3,100.0
4,26.0
5,13.0
6,31.0
7,50.0


In [32]:
miles.isna()

,farthest_run_mi
0,False
1,False
2,True
3,False
4,False
5,False
6,False
7,False


In [33]:
from sklearn.impute import SimpleImputer

In [34]:
imp_mean=SimpleImputer(strategy='mean')

In [35]:
imp_mean.fit_transform(miles)

array([[ 50.        ],
       [ 62.        ],
       [ 47.42857143],
       [100.        ],
       [ 26.        ],
       [ 13.        ],
       [ 31.        ],
       [ 50.        ]])

In [36]:
imp_median=SimpleImputer(strategy='median')

In [37]:
imp_median.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [38]:
imp_mode=SimpleImputer(strategy='most_frequent')

In [39]:
imp_mode.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [40]:
imp_constant=SimpleImputer(strategy='constant', fill_value=13)

In [41]:
imp_constant.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 13.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [42]:
names = pd.DataFrame({'names': ['ayush','aman','harish','ram', np.nan, 'adi']})

names

,names
0,ayush
1,aman
2,harish
3,ram
4,NaN
5,adi


In [43]:
imp_constant_cat=SimpleImputer(strategy='constant', fill_value='babe')

In [44]:
imp_constant_cat.fit_transform(names)

array([['ayush'],
       ['aman'],
       ['harish'],
       ['ram'],
       ['babe'],
       ['adi']], dtype=object)

In [45]:
imp_mean_marked=SimpleImputer(strategy='mean', add_indicator=True)

In [46]:
imp_mean_marked.fit_transform(miles)

array([[ 50.        ,   0.        ],
       [ 62.        ,   0.        ],
       [ 47.42857143,   1.        ],
       [100.        ,   0.        ],
       [ 26.        ,   0.        ],
       [ 13.        ,   0.        ],
       [ 31.        ,   0.        ],
       [ 50.        ,   0.        ]])

In [47]:
from sklearn.compose import make_column_transformer

In [48]:
ct = make_column_transformer(
(imp_constant_cat, ['Name']),
(imp_mean, ['farthest_run_mi']),
remainder='drop'
)

In [49]:
df_pandas=ct.fit_transform(df)

NameError: name 'df' is not defined

In [ ]:
df_panads