##Numpy array basics 



##creating array from list 

In [3]:
import numpy as np
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


##list vs numpy array


In [5]:
py_list = [1,2,3]
print("python list multiplication", py_list*2)

np_array = np.array([1,2,3]) #element wise muyliplication
print("Pyhton array multiplication", np_array*2)

import time 
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n list operation time: ", time.time()- start)

start=time.time()
np_array = np.arange(1000000) * 2
print("\n numpy  operation time: ", time.time()- start)

python list multiplication [1, 2, 3, 1, 2, 3]
Pyhton array multiplication [2 4 6]

 list operation time:  0.1084601879119873

 numpy  operation time:  0.013942956924438477


##creating arry from scratch


In [7]:
zeroes = np.zeros((3,4))
print(zeroes)

ones = np.ones((2,3))
print(ones)

full = np.full((2,2), 7)
print(full)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]


##vector, matrix and tensor

In [8]:
vector = np.array([1,2,3])
print("vector", vector)

matrix = np.array([[1,2,3], [5,7,8]])
print("mayrix", matrix)

tensor = np.array([[[1,2],[3,4]],
                    [[5,6], [7,8]] ])
print("tensor", tensor)

vector [1 2 3]
mayrix [[1 2 3]
 [5 7 8]]
tensor [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


##array properties 

In [10]:
arr = np.array([[1,2,3], [4,5,6]])
print("Shape", arr.shape)
print("dimension", arr.ndim)
print("size", arr.size)
print("data type", arr.dtype)

Shape (2, 3)
dimension 2
size 6
data type int64


##array reshaping

In [13]:
arr = np.arange(12) #arange(start(inclusive), stop(exclusive), step)
print("original array ", arr)

reshaped = arr.reshape((3,4))
print("reshaped array", reshaped)

flattened = reshaped.flatten() #cganges in copy 
print(flattened)

#ravel returns view instead of copy 
raveled = reshaped.ravel()
print("raveled array", raveled)

#transpose
transpose = reshaped.T
print("transposed array", transpose)


original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
